kind: pipeline
name: default
steps:
- name: build
  image: node:12
  commands:
  - npm install
  - npm test
  - npm run build
- name: npm
  image: plugins/npm
  settings:
    token:
      from_secret: npm_token
  when:
    event: tag
---
kind: secret
name: npm_token
data: I3k2YwirwX+5c3mU+DXGsE7qVsFJBJyeNP28Sv7HOFlKH+qiJqjZFwNg/QAl1J1RKioivcD4yLM6Cdp/tDm+6g==
  
